version: "3.9"

networks:
  tm-net:
    driver: bridge
services:
  api:    
    container_name: taskManager
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   
      - ASPNETCORE_HTTP_PORTS=5282    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5282:5282"
    networks:
      - tm-net
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=123
      -  POSTGRES_DB=tm
    ports:
      - "5432:5432"
    networks:
      - tm-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:    